name: Linux Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up dependencies
        run: sudo apt install gcc-10 llvm-10
      - name: Configure
        working-directory: ${{ github.workspace }}
        run: cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.config }} -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.config }}
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure
    strategy:
      matrix:
        config: [Release, Debug, RelWithDebInfo, MinSizeRel]
        compiler: [g++-10, clang++]
