name: CMake CI

on: push

jobs:
  linux:
    name: Run - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up dependencies
        run: sudo apt install gcc-10 llvm-10
      - name: Configure
        working-directory: ${{ github.workspace }}
        run: cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.config }} -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.config }}
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest
    strategy:
      matrix:
        config: [Release, Debug, RelWithDebInfo, MinSizeRel]
        compiler: [g++-10, clang++]
  windows:
    name: Run - Windows
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Configure
        working-directory: ${{ github.workspace }}
        run: cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.config }}
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.config }}
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.config }}
    strategy:
      matrix:
        config: [Release, Debug, RelWithDebInfo, MinSizeRel]
  macos:
    name: Run - MacOS
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Configure
        working-directory: ${{ github.workspace }}
        run: cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.config }}
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.config }}
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.config }}
    strategy:
      matrix:
        config: [Release, Debug, RelWithDebInfo, MinSizeRel]
