name: Windows Build

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Configure
        working-directory: ${{ github.workspace }}
        run: cmake -B build -D CMAKE_BUILD_TYPE=${{ matrix.config }}
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.config }}
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.config }} --output-on-failure
    strategy:
      matrix:
        config: [Release, Debug, RelWithDebInfo, MinSizeRel]
